// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-XeAiC1ne1TuF98T-g2CtKKJwxfMFWnE',
    appId: '1:222697904239:web:bf012106626424371d159a',
    messagingSenderId: '222697904239',
    projectId: 'civic-connect-857f9',
    authDomain: 'civic-connect-857f9.firebaseapp.com',
    databaseURL: 'https://civic-connect-857f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'civic-connect-857f9.firebasestorage.app',
    measurementId: 'G-2CDZ8NZFWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA88neGB7IZiRakg7yJenfeHXFrJDEsCPw',
    appId: '1:222697904239:android:03cb611b99320bd71d159a',
    messagingSenderId: '222697904239',
    projectId: 'civic-connect-857f9',
    databaseURL: 'https://civic-connect-857f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'civic-connect-857f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSujMh9l75CKH5JzBtmXUhsBIkifX8D2k',
    appId: '1:222697904239:ios:c4fee9335f0993c11d159a',
    messagingSenderId: '222697904239',
    projectId: 'civic-connect-857f9',
    databaseURL: 'https://civic-connect-857f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'civic-connect-857f9.firebasestorage.app',
    iosBundleId: 'com.example.civicConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSujMh9l75CKH5JzBtmXUhsBIkifX8D2k',
    appId: '1:222697904239:ios:c4fee9335f0993c11d159a',
    messagingSenderId: '222697904239',
    projectId: 'civic-connect-857f9',
    databaseURL: 'https://civic-connect-857f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'civic-connect-857f9.firebasestorage.app',
    iosBundleId: 'com.example.civicConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-XeAiC1ne1TuF98T-g2CtKKJwxfMFWnE',
    appId: '1:222697904239:web:1330e488ed6f7daf1d159a',
    messagingSenderId: '222697904239',
    projectId: 'civic-connect-857f9',
    authDomain: 'civic-connect-857f9.firebaseapp.com',
    databaseURL: 'https://civic-connect-857f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'civic-connect-857f9.firebasestorage.app',
    measurementId: 'G-LH8JY6YL4Y',
  );
}
